using FiscalOS.LegalKnowledge;
using FiscalOS.LegalKnowledge.Corpus;
using Xunit;

namespace FiscalOS.VerticalSliceTests;

public sealed class Should_Run_Corpus01_Step5_Phase4
{
    private static (SemanticKnowledgeCandidate C, SemanticCurationDecision D) Make(DateTimeOffset k, LegalValidTime? l, string text="text", string? supersedes=null, SemanticCurationDisposition disp=SemanticCurationDisposition.Accepted)
    { var a=new FiscalOS.LegalKnowledge.Corpus.StructuralAtom("a",FiscalOS.LegalKnowledge.Corpus.StructuralAtomType.Article,"1",null,0,0,4,"atom-v1",new[]{new FiscalOS.LegalKnowledge.Corpus.NormalizedSourceSpan("raw",0,4,0,4)}); var doc=new FiscalOS.LegalKnowledge.Corpus.StructuralLegalDocument("atom-v1",new[]{a}){RawArtifactId="raw",NormalizationVersion="norm-v1"}; var cd=new FiscalOS.LegalKnowledge.Corpus.CurationDecision("c","raw","atom-v1","norm-v1",FiscalOS.LegalKnowledge.Corpus.CurationDisposition.Accepted,"ok",new[]{"a"},false,DateTimeOffset.UnixEpoch,"r",FiscalOS.LegalKnowledge.Corpus.StructuralCuration.Version); var c=SemanticKnowledgeCandidate.Create(SemanticKnowledgeKind.LegalDefinition,"term",text,new FiscalOS.LegalKnowledge.Corpus.CuratedStructuralMaterial(cd,doc),new[]{"a"},new StableLegalScope("RO:Law:1/2020","Article/1")).Candidate!; var d=SemanticCuration.Decide(c,c,disp,"reason","reviewer",k,l).Decision! with {SupersedesSemanticDecisionId=supersedes}; return(c,d); }
    [Fact] public void Valid_legal_valid_time_is_explicit() { var r=LegalValidTime.Create(new DateOnly(2026,1,1),new DateOnly(2026,12,31)); Assert.Equal(SemanticCurationError.None,r.Error); Assert.Equal(new DateOnly(2026,1,1),r.Value!.ValidFrom); }
    [Fact] public void Invalid_legal_valid_range_is_typed_error() { Assert.Equal(SemanticCurationError.InvalidLegalValidRange,LegalValidTime.Create(new DateOnly(2026,2,1),new DateOnly(2026,1,1)).Error); Assert.Equal(SemanticCurationError.MissingLegalValidFrom,LegalValidTime.Create(null,null).Error); }
    [Fact] public void Legal_valid_time_is_not_inferred_from_knowledge_time() { var r=LegalValidTime.Create(new DateOnly(2020,1,1),null); Assert.Equal(SemanticCurationError.None,r.Error); Assert.NotEqual(DateOnly.FromDateTime(DateTime.UtcNow),r.Value!.ValidFrom); }
    [Fact] public void Legal_valid_time_is_independent_value() { var a=new LegalValidTime(new DateOnly(2026,1,1)); var b=new LegalValidTime(new DateOnly(2026,1,1)); Assert.Equal(a,b); }
    [Fact] public async Task Bitemporal_query_uses_closed_interval_and_knowledge_cutoff() { var p=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString()); var l=new LegalValidTime(new DateOnly(2026,1,1),new DateOnly(2026,12,31)); var x=Make(DateTimeOffset.Parse("2026-02-01Z"),l); await new FileSemanticKnowledgeRepository(p).SaveAsync(x.C,x.D); var r=new FileSemanticKnowledgeRepository(p); Assert.Equal(SemanticAsOfStatus.NotFound,(await r.GetAsOfAsync(x.C.SemanticConceptId,new DateOnly(2026,1,1),DateTimeOffset.Parse("2026-01-01Z"))).Status); Assert.Equal(SemanticAsOfStatus.Found,(await r.GetAsOfAsync(x.C.SemanticConceptId,new DateOnly(2026,1,1),DateTimeOffset.Parse("2026-02-01Z"))).Status); Assert.Equal(SemanticAsOfStatus.Found,(await r.GetAsOfAsync(x.C.SemanticConceptId,new DateOnly(2026,12,31),DateTimeOffset.Parse("2026-03-01Z"))).Status); Assert.Equal(SemanticAsOfStatus.NotFound,(await r.GetAsOfAsync(x.C.SemanticConceptId,new DateOnly(2027,1,1),DateTimeOffset.Parse("2026-03-01Z"))).Status); }
    [Fact] public async Task Null_legal_valid_time_round_trips() { var x=Make(DateTimeOffset.Parse("2026-01-01Z"),null); var p=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString()); await new FileSemanticKnowledgeRepository(p).SaveAsync(x.C,x.D); Assert.Null((await new FileSemanticKnowledgeRepository(p).GetDecisionAsync(x.D.SemanticCurationDecisionId))!.LegalValidTime); }
    [Fact] public async Task Open_ended_legal_valid_time_round_trips() { var l=new LegalValidTime(new DateOnly(2026,1,1)); var x=Make(DateTimeOffset.Parse("2026-01-01Z"),l); var p=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString()); await new FileSemanticKnowledgeRepository(p).SaveAsync(x.C,x.D); Assert.Equal(l,(await new FileSemanticKnowledgeRepository(p).GetDecisionAsync(x.D.SemanticCurationDecisionId))!.LegalValidTime); }
    [Fact] public async Task Bounded_legal_valid_time_round_trips() { var l=new LegalValidTime(new DateOnly(2026,1,1),new DateOnly(2026,12,31)); var x=Make(DateTimeOffset.Parse("2026-01-01Z"),l); var p=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString()); await new FileSemanticKnowledgeRepository(p).SaveAsync(x.C,x.D); Assert.Equal(l,(await new FileSemanticKnowledgeRepository(p).GetDecisionAsync(x.D.SemanticCurationDecisionId))!.LegalValidTime); }
    [Fact] public async Task Decision_id_survives_reload() { var x=Make(DateTimeOffset.Parse("2026-01-01Z"),new LegalValidTime(new DateOnly(2026,1,1))); var p=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString()); await new FileSemanticKnowledgeRepository(p).SaveAsync(x.C,x.D); Assert.Equal(x.D.SemanticCurationDecisionId,(await new FileSemanticKnowledgeRepository(p).GetDecisionAsync(x.D.SemanticCurationDecisionId))!.SemanticCurationDecisionId); }
    [Fact] public async Task Rejected_and_needs_review_never_resolve() { foreach(var d in new[]{SemanticCurationDisposition.Rejected,SemanticCurationDisposition.NeedsReview}) { var x=Make(DateTimeOffset.Parse("2026-01-01Z"),new LegalValidTime(new DateOnly(2026,1,1)),disp:d); var p=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString()); await new FileSemanticKnowledgeRepository(p).SaveAsync(x.C,x.D); Assert.Equal(SemanticAsOfStatus.NotFound,(await new FileSemanticKnowledgeRepository(p).GetAsOfAsync(x.C.SemanticConceptId,new DateOnly(2026,1,1),DateTimeOffset.Parse("2026-02-01Z"))).Status); } }
    [Fact] public async Task ValidFrom_tamper_is_rejected() { var x=Make(DateTimeOffset.Parse("2026-01-01Z"),new LegalValidTime(new DateOnly(2026,1,1))); var p=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString()); await new FileSemanticKnowledgeRepository(p).SaveAsync(x.C,x.D); var f=Path.Combine(p,"semantic-knowledge.jsonl"); var s=await File.ReadAllTextAsync(f); await File.WriteAllTextAsync(f,s.Replace("2026-01-01","2026-02-01")); await Assert.ThrowsAsync<InvalidDataException>(async()=>await new FileSemanticKnowledgeRepository(p).GetHistoryAsync(x.C.SemanticConceptId)); }
    [Fact] public async Task ValidTo_tamper_is_rejected() { var x=Make(DateTimeOffset.Parse("2026-01-01Z"),new LegalValidTime(new DateOnly(2026,1,1),new DateOnly(2026,12,31))); var p=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString()); await new FileSemanticKnowledgeRepository(p).SaveAsync(x.C,x.D); var f=Path.Combine(p,"semantic-knowledge.jsonl"); var s=await File.ReadAllTextAsync(f); await File.WriteAllTextAsync(f,s.Replace("2026-12-31","2026-11-30")); await Assert.ThrowsAsync<InvalidDataException>(async()=>await new FileSemanticKnowledgeRepository(p).GetHistoryAsync(x.C.SemanticConceptId)); }
    [Fact] public async Task Historical_correction_after_later_persistence_preserves_old_query() { var p=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString()); var l=new LegalValidTime(new DateOnly(2026,1,1)); var a=Make(DateTimeOffset.Parse("2026-01-10Z"),l); var r=new FileSemanticKnowledgeRepository(p); await r.SaveAsync(a.C,a.D); var b=Make(DateTimeOffset.Parse("2026-02-10Z"),l,"corrected",a.D.SemanticCurationDecisionId); await r.SaveAsync(b.C,b.D); var q=new FileSemanticKnowledgeRepository(p); Assert.Equal(a.C.SemanticCandidateId,(await q.GetAsOfAsync(a.C.SemanticConceptId,new DateOnly(2026,1,15),DateTimeOffset.Parse("2026-01-20Z"))).Knowledge!.Candidate.SemanticCandidateId); Assert.Equal(b.C.SemanticCandidateId,(await q.GetAsOfAsync(a.C.SemanticConceptId,new DateOnly(2026,1,15),DateTimeOffset.Parse("2026-03-01Z"))).Knowledge!.Candidate.SemanticCandidateId); }
    [Fact] public async Task Overlapping_accepted_versions_are_ambiguous() { var p=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString()); var l=new LegalValidTime(new DateOnly(2026,1,1)); var a=Make(DateTimeOffset.Parse("2026-01-01Z"),l); var b=Make(DateTimeOffset.Parse("2026-01-02Z"),l,"other"); var r=new FileSemanticKnowledgeRepository(p); await r.SaveAsync(a.C,a.D); await r.SaveAsync(b.C,b.D); Assert.Equal(SemanticAsOfStatus.Ambiguous,(await r.GetAsOfAsync(a.C.SemanticConceptId,new DateOnly(2026,1,2),DateTimeOffset.Parse("2026-02-01Z"))).Status); }
    [Fact] public async Task Real_fixture_bitemporal_correction_survives_restart() { var path=Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"..","..","..","..","..","tests","FiscalOS.VerticalSliceTests","Fixtures","corpus","legea-227-2015-official.html")); var bytes=await File.ReadAllBytesAsync(path); var h=FileRawLegalCorpusRepository.Hash(bytes); var art=new RawCorpusArtifact("raw:"+h,"legea-227-2015-official.html","text/html",bytes.Length,h,SourceClassification.OfficialPortal,null,null,DateTimeOffset.UnixEpoch,null,null,DocumentForm.Base,path); var n=LegalCorpusNormalizer.Normalize(art,bytes); var sd=LegalStructuralAtomizer.Atomize(n); var atom=sd.Atoms.First(a=>a.AtomType==StructuralAtomType.Article); var cr=StructuralCuration.Decide(sd,art.RawArtifactId,n.NormalizationVersion,CurationDisposition.Accepted,"ok",new[]{atom.StructuralAtomId},false,DateTimeOffset.UnixEpoch,"reviewer"); var material=cr.Material!; var scope=new StableLegalScope("RO:Law:227/2015",atom.Designation); var v1=SemanticKnowledgeCandidate.Create(SemanticKnowledgeKind.LegalDefinition,"termen","v1",material,new[]{atom.StructuralAtomId},scope).Candidate!; var l=new LegalValidTime(new DateOnly(2026,1,1)); var a=SemanticCuration.Decide(v1,v1,SemanticCurationDisposition.Accepted,"r","u",DateTimeOffset.Parse("2026-01-10Z"),l).Decision!; var p=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString()); await new FileSemanticKnowledgeRepository(p).SaveAsync(v1,a); var v2=SemanticKnowledgeCandidate.Create(SemanticKnowledgeKind.LegalDefinition,"termen","v2",material,new[]{atom.StructuralAtomId},scope).Candidate!; var b=SemanticCuration.Decide(v2,v2,SemanticCurationDisposition.Accepted,"r2","u",DateTimeOffset.Parse("2026-02-10Z"),l).Decision! with {SupersedesSemanticDecisionId=a.SemanticCurationDecisionId}; await new FileSemanticKnowledgeRepository(p).SaveAsync(v2,b); var r=new FileSemanticKnowledgeRepository(p); Assert.Equal(v1.SemanticCandidateId,(await r.GetAsOfAsync(v1.SemanticConceptId,new DateOnly(2026,1,2),DateTimeOffset.Parse("2026-01-20Z"))).Knowledge!.Candidate.SemanticCandidateId); Assert.Equal(v2.SemanticCandidateId,(await r.GetAsOfAsync(v1.SemanticConceptId,new DateOnly(2026,1,2),DateTimeOffset.Parse("2026-03-01Z"))).Knowledge!.Candidate.SemanticCandidateId); Assert.Equal(2,(await r.GetHistoryAsync(v1.SemanticConceptId)).Count); }
}
