using FiscalOS.LegalKnowledge;
using FiscalOS.LegalKnowledge.Corpus;
using System.Text.Json;
using Xunit;

namespace FiscalOS.VerticalSliceTests;

public sealed class Should_Run_Corpus01_Step5_Phase3
{
    private static (SemanticKnowledgeCandidate C, SemanticCurationDecision D) Make(string text = "text", string? supersedes = null, SemanticCurationDisposition disposition = SemanticCurationDisposition.Accepted, DateTimeOffset? time = null, string raw = "raw")
    {
        var atom = new StructuralAtom("a", StructuralAtomType.Article, "1", null, 0, 0, 4, "atom-v1", new[] { new NormalizedSourceSpan(raw, 0, 4, 0, 4) });
        var doc = new StructuralLegalDocument("atom-v1", new[] { atom }) { RawArtifactId = raw, NormalizationVersion = "norm-v1" };
        var cd = new CurationDecision("c-" + raw, raw, "atom-v1", "norm-v1", CurationDisposition.Accepted, "ok", new[] { "a" }, false, DateTimeOffset.UnixEpoch, "r", StructuralCuration.Version);
        var material = new CuratedStructuralMaterial(cd, doc);
        var c = SemanticKnowledgeCandidate.Create(SemanticKnowledgeKind.LegalDefinition, "term", text, material, new[] { "a" }, new StableLegalScope("RO:Law:1/2020", "Article/1")).Candidate!;
        var d = SemanticCuration.Decide(c, c, disposition, "reason", "reviewer", time ?? DateTimeOffset.Parse("2026-01-01T00:00:00Z")).Decision! with { SupersedesSemanticDecisionId = supersedes };
        return (c, d);
    }
    private static string Dir() => Path.Combine(Path.GetTempPath(), "fos-sem-" + Guid.NewGuid().ToString("N"));

    [Fact] public async Task Accepted_semantic_decision_survives_restart_reload() { var p=Dir(); var x=Make(); await new FileSemanticKnowledgeRepository(p).SaveAsync(x.C,x.D); var r=new FileSemanticKnowledgeRepository(p); Assert.Equal(x.D,await r.GetDecisionAsync(x.D.SemanticCurationDecisionId)); Assert.Equal(x.C,await r.GetCandidateAsync(x.C.SemanticCandidateId)); }
    [Fact] public async Task Rejected_decision_survives_history_without_promotion() { var x=Make(disposition:SemanticCurationDisposition.Rejected); var p=Dir(); await new FileSemanticKnowledgeRepository(p).SaveAsync(x.C,x.D); Assert.Single(await new FileSemanticKnowledgeRepository(p).GetHistoryAsync(x.C.SemanticConceptId)); Assert.Null(SemanticCuration.Promote(x.C,x.D)); }
    [Fact] public async Task NeedsReview_decision_survives_history_without_promotion() { var x=Make(disposition:SemanticCurationDisposition.NeedsReview); var p=Dir(); await new FileSemanticKnowledgeRepository(p).SaveAsync(x.C,x.D); Assert.Single(await new FileSemanticKnowledgeRepository(p).GetHistoryAsync(x.C.SemanticConceptId)); Assert.Null(SemanticCuration.Promote(x.C,x.D)); }
    [Fact] public async Task Semantic_correction_A_to_B_preserves_A() { var p=Dir(); var a=Make(); await new FileSemanticKnowledgeRepository(p).SaveAsync(a.C,a.D); var b=Make("corrected",a.D.SemanticCurationDecisionId); await new FileSemanticKnowledgeRepository(p).SaveAsync(b.C,b.D); var r=new FileSemanticKnowledgeRepository(p); Assert.NotNull(await r.GetDecisionAsync(a.D.SemanticCurationDecisionId)); Assert.Equal(a.D.SemanticCurationDecisionId,(await r.GetDecisionAsync(b.D.SemanticCurationDecisionId))!.SupersedesSemanticDecisionId); Assert.NotEqual(a.C.SemanticCandidateId,b.C.SemanticCandidateId); }
    [Fact] public async Task Semantic_correction_A_to_B_to_C_survives_restart() { var p=Dir(); var a=Make(); var repo=new FileSemanticKnowledgeRepository(p); await repo.SaveAsync(a.C,a.D); var b=Make("b",a.D.SemanticCurationDecisionId); await repo.SaveAsync(b.C,b.D); var c=Make("c",b.D.SemanticCurationDecisionId); await repo.SaveAsync(c.C,c.D); Assert.Equal(3,(await new FileSemanticKnowledgeRepository(p).GetHistoryAsync(a.C.SemanticConceptId)).Count); }
    [Fact] public async Task Unknown_semantic_predecessor_returns_typed_error() { var x=Make(supersedes:"missing"); Assert.Equal(SemanticPersistenceError.UnknownSemanticPredecessor,(await new FileSemanticKnowledgeRepository(Dir()).SaveAsync(x.C,x.D)).Error); }
    [Fact] public async Task Self_semantic_supersession_returns_typed_error() { var x=Make(); var d=x.D with { SupersedesSemanticDecisionId=x.D.SemanticCurationDecisionId }; Assert.Equal(SemanticPersistenceError.SelfSemanticSupersession,(await new FileSemanticKnowledgeRepository(Dir()).SaveAsync(x.C,d)).Error); }
    [Fact] public async Task Semantic_supersession_cycle_returns_typed_error() { var p=Dir(); var a=Make(); var repo=new FileSemanticKnowledgeRepository(p); await repo.SaveAsync(a.C,a.D); var b=Make("b",a.D.SemanticCurationDecisionId); await repo.SaveAsync(b.C,b.D); var cyc=b.D with { SupersedesSemanticDecisionId=b.D.SemanticCurationDecisionId }; Assert.Equal(SemanticPersistenceError.SelfSemanticSupersession,(await repo.SaveAsync(b.C,cyc)).Error); }
    [Fact] public async Task Cross_concept_semantic_supersession_returns_typed_error() { var p=Dir(); var a=Make(); var repo=new FileSemanticKnowledgeRepository(p); await repo.SaveAsync(a.C,a.D); var other=Make("x",a.D.SemanticCurationDecisionId); var d=other.D with { SemanticConceptId="concept:other" }; Assert.Equal(SemanticPersistenceError.SemanticConceptMismatchAcrossSupersession,(await repo.SaveAsync(other.C,d)).Error); }
    [Fact] public async Task Semantic_history_is_deterministic() { var p=Dir(); var a=Make(time:DateTimeOffset.Parse("2026-01-02Z")); var b=Make("b",time:DateTimeOffset.Parse("2026-01-01Z")); var repo=new FileSemanticKnowledgeRepository(p); await repo.SaveAsync(a.C,a.D); await repo.SaveAsync(b.C,b.D); var h=await new FileSemanticKnowledgeRepository(p).GetHistoryAsync(a.C.SemanticConceptId); Assert.Equal(new[]{b.D.SemanticCurationDecisionId,a.D.SemanticCurationDecisionId},h.Select(x=>x.SemanticCurationDecisionId)); }
    [Fact] public async Task KnowledgeTime_survives_restart_exactly() { var x=Make(time:DateTimeOffset.Parse("2026-04-05T12:34:56+03:00")); var p=Dir(); await new FileSemanticKnowledgeRepository(p).SaveAsync(x.C,x.D); Assert.Equal(x.D.KnowledgeTime,(await new FileSemanticKnowledgeRepository(p).GetDecisionAsync(x.D.SemanticCurationDecisionId))!.KnowledgeTime); }
    [Fact] public async Task Candidate_payload_and_grounding_survive_restart() { var x=Make(); var p=Dir(); await new FileSemanticKnowledgeRepository(p).SaveAsync(x.C,x.D); Assert.Equal(x.C,await new FileSemanticKnowledgeRepository(p).GetCandidateAsync(x.C.SemanticCandidateId)); }
    [Fact] public async Task Malformed_semantic_record_is_rejected() { var p=Dir(); Directory.CreateDirectory(p); await File.WriteAllTextAsync(Path.Combine(p,"semantic-knowledge.jsonl"),"not-json\n"); await Assert.ThrowsAsync<JsonException>(async()=>await new FileSemanticKnowledgeRepository(p).GetHistoryAsync("x")); }
    [Fact] public void Semantic_persistence_has_no_forbidden_dependencies() { var refs=typeof(FileSemanticKnowledgeRepository).Assembly.GetReferencedAssemblies().Select(x=>x.Name); Assert.DoesNotContain("FiscalOS.Runtime",refs); }
    [Fact] public async Task Tampered_candidate_id_is_rejected_on_reload() { var p=Dir(); var x=Make(); await new FileSemanticKnowledgeRepository(p).SaveAsync(x.C,x.D); var f=Path.Combine(p,"semantic-knowledge.jsonl"); var s=await File.ReadAllTextAsync(f); await File.WriteAllTextAsync(f,s.Replace(x.C.SemanticCandidateId,"candidate:tampered")); await Assert.ThrowsAsync<InvalidDataException>(async()=>await new FileSemanticKnowledgeRepository(p).GetHistoryAsync(x.C.SemanticConceptId)); }
    [Fact] public async Task Tampered_decision_id_is_rejected_on_reload() { var p=Dir(); var x=Make(); await new FileSemanticKnowledgeRepository(p).SaveAsync(x.C,x.D); var f=Path.Combine(p,"semantic-knowledge.jsonl"); var s=await File.ReadAllTextAsync(f); await File.WriteAllTextAsync(f,s.Replace(x.D.SemanticCurationDecisionId,"semantic-curation:tampered")); await Assert.ThrowsAsync<InvalidDataException>(async()=>await new FileSemanticKnowledgeRepository(p).GetHistoryAsync(x.C.SemanticConceptId)); }
    [Fact] public async Task Semantic_correction_is_physically_append_only() { var p=Dir(); var a=Make(); var r=new FileSemanticKnowledgeRepository(p); await r.SaveAsync(a.C,a.D); var f=Path.Combine(p,"semantic-knowledge.jsonl"); var before=await File.ReadAllBytesAsync(f); var b=Make("b",a.D.SemanticCurationDecisionId); await r.SaveAsync(b.C,b.D); var after=await File.ReadAllBytesAsync(f); Assert.True(after.Length>before.Length); Assert.Equal(before,after[..before.Length]); }
    [Fact] public async Task Identical_duplicate_save_is_physical_no_op() { var p=Dir(); var x=Make(); var r=new FileSemanticKnowledgeRepository(p); await r.SaveAsync(x.C,x.D); var f=Path.Combine(p,"semantic-knowledge.jsonl"); var before=await File.ReadAllBytesAsync(f); await r.SaveAsync(x.C,x.D); Assert.Equal(before,await File.ReadAllBytesAsync(f)); }
    [Fact] public async Task Missing_candidate_is_rejected_on_reload() { var p=Dir(); var x=Make(); var r=new FileSemanticKnowledgeRepository(p); await r.SaveAsync(x.C,x.D); var f=Path.Combine(p,"semantic-knowledge.jsonl"); var s=await File.ReadAllTextAsync(f); await File.WriteAllTextAsync(f,s.Replace("\"CandidateId\":\""+x.C.SemanticCandidateId+"\"","\"CandidateId\":\"candidate:missing\"")); await Assert.ThrowsAsync<InvalidDataException>(async()=>await new FileSemanticKnowledgeRepository(p).GetHistoryAsync(x.C.SemanticConceptId)); }
    [Fact] public async Task Real_fixture_semantic_correction_survives_restart_with_provenance() { var fixture=Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"..","..","..","..","..","tests","FiscalOS.VerticalSliceTests","Fixtures","corpus","legea-227-2015-official.html")); var bytes=await File.ReadAllBytesAsync(fixture); var hash=FileRawLegalCorpusRepository.Hash(bytes); var art=new RawCorpusArtifact("raw:"+hash,"legea-227-2015-official.html","text/html",bytes.Length,hash,SourceClassification.OfficialPortal,"https://legislatie.just.ro/Public/DetaliiDocument/171280","171280",DateTimeOffset.UnixEpoch,"MO 688/2015",new LegalActIdentity("RO",LegalActType.Law,227,2015),DocumentForm.Base,fixture); var n=LegalCorpusNormalizer.Normalize(art,bytes); var sd=LegalStructuralAtomizer.Atomize(n); var atom=sd.Atoms.First(a=>a.AtomType==StructuralAtomType.Article); var cr=StructuralCuration.Decide(sd,art.RawArtifactId,n.NormalizationVersion,CurationDisposition.Accepted,"reviewed",new[]{atom.StructuralAtomId},false,DateTimeOffset.UnixEpoch,"reviewer"); var c=SemanticKnowledgeCandidate.Create(SemanticKnowledgeKind.LegalDefinition,"termen", "definitie V1",cr.Material!,new[]{atom.StructuralAtomId},new StableLegalScope("RO:Law:227/2015",atom.Designation)).Candidate!; var a=SemanticCuration.Decide(c,c,SemanticCurationDisposition.Accepted,"explicit","reviewer",DateTimeOffset.Parse("2026-01-01Z")).Decision!; var p=Dir(); await new FileSemanticKnowledgeRepository(p).SaveAsync(c,a); var c2=SemanticKnowledgeCandidate.Create(SemanticKnowledgeKind.LegalDefinition,"termen","definitie V2",cr.Material!,new[]{atom.StructuralAtomId},new StableLegalScope("RO:Law:227/2015",atom.Designation)).Candidate!; var b=SemanticCuration.Decide(c2,c2,SemanticCurationDisposition.Accepted,"correction","reviewer",DateTimeOffset.Parse("2026-02-01Z")).Decision! with { SupersedesSemanticDecisionId=a.SemanticCurationDecisionId }; await new FileSemanticKnowledgeRepository(p).SaveAsync(c2,b); var h=await new FileSemanticKnowledgeRepository(p).GetHistoryAsync(c.SemanticConceptId); Assert.Equal(2,h.Count); Assert.Equal(a.SemanticCurationDecisionId,h[0].SemanticCurationDecisionId); Assert.Equal(a.SemanticCurationDecisionId,b.SupersedesSemanticDecisionId); Assert.Equal(c.Grounding.RawArtifactId,c2.Grounding.RawArtifactId); Assert.NotEqual(c.SemanticCandidateId,c2.SemanticCandidateId); }
}
